# Generated by Django 2.2.12 on 2022-09-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_campus', models.IntegerField()),
                ('Name_campus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_conditions', models.IntegerField()),
                ('Subject_condition', models.IntegerField()),
                ('Type_condition', models.CharField(max_length=5)),
                ('Number_subject', models.IntegerField()),
                ('All_subjects', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_curriculum', models.IntegerField()),
                ('Name_curriculum', models.CharField(max_length=50)),
                ('Id_faculty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_faculty', models.IntegerField()),
                ('Name_faculty', models.CharField(max_length=50)),
                ('Id_campus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_group', models.IntegerField()),
                ('Modality', models.CharField(max_length=30)),
                ('Teacher', models.CharField(max_length=50)),
                ('Date_start', models.DateField()),
                ('Date_finish', models.DateField()),
                ('Duration', models.CharField(max_length=15)),
                ('Working_day', models.CharField(max_length=15)),
                ('Supply_places', models.IntegerField()),
                ('Id_faculty', models.IntegerField()),
                ('Id_subject', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_place', models.IntegerField()),
                ('Place_tower', models.TextField()),
                ('Place_salon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_schedule', models.IntegerField()),
                ('Star_time', models.DateField()),
                ('End_time', models.DateField()),
                ('Id_place', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_subject', models.IntegerField()),
                ('Name_subject', models.CharField(max_length=50)),
                ('Typology', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('Id_curriculum', models.IntegerField()),
            ],
        ),
    ]
