# Generated by Django 2.2.12 on 2022-09-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buscador', '0015_auto_20220912_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Id_career',
            field=models.ManyToManyField(to='Buscador.Career'),
        ),
    ]
