# Generated by Django 2.2.12 on 2022-09-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('Id_campus', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_campus', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('Id_career', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_career', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('Id_condition', models.IntegerField(primary_key=True, serialize=False)),
                ('number_condition', models.IntegerField(default=0)),
                ('Number_subject', models.IntegerField()),
                ('All_subjects', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('Id_place', models.IntegerField(primary_key=True, serialize=False)),
                ('Place_numbertower', models.IntegerField()),
                ('Place_nametower', models.CharField(max_length=200)),
                ('Place_numbersalon', models.IntegerField()),
                ('Place_namesalon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subjectsconditions',
            fields=[
                ('Id_Subjectconditions', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_subjectconditions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Types_Conditions',
            fields=[
                ('Id_types', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Types_Typologys',
            fields=[
                ('Id_typology', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_typology', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Id_subject', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_subject', models.CharField(max_length=100)),
                ('Credits', models.IntegerField()),
                ('Description', models.TextField()),
                ('Id_career', models.ManyToManyField(to='Buscador.Career')),
                ('Id_condition', models.ManyToManyField(to='Buscador.Condition')),
                ('Typology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Buscador.Types_Typologys')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('Id_Schedule', models.IntegerField(primary_key=True, serialize=False)),
                ('day_name', models.CharField(default='Sin dia', max_length=30)),
                ('Star_time', models.TimeField(blank=True, null=True)),
                ('End_time', models.TimeField(blank=True, null=True)),
                ('Id_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='Buscador.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('Id_group', models.IntegerField(primary_key=True, serialize=False)),
                ('Modality', models.CharField(max_length=40)),
                ('Teacher', models.CharField(max_length=100)),
                ('Date_start', models.DateField()),
                ('Date_finish', models.DateField()),
                ('Duration', models.CharField(max_length=15)),
                ('Working_day', models.CharField(max_length=15)),
                ('Slots', models.IntegerField()),
                ('Id_faculty', models.IntegerField()),
                ('Id_sheduler', models.ManyToManyField(to='Buscador.Schedule')),
                ('Id_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Buscador.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Id_faculty', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_faculty', models.CharField(max_length=100)),
                ('Id_campus', models.ManyToManyField(blank=True, related_name='Facultys', to='Buscador.Campus')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='Subject_condition',
            field=models.ManyToManyField(blank=True, related_name='Subjects_Conditions', to='Buscador.Subjectsconditions'),
        ),
        migrations.AddField(
            model_name='condition',
            name='Type_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Buscador.Types_Conditions'),
        ),
        migrations.AddField(
            model_name='career',
            name='Id_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Buscador.Faculty'),
        ),
    ]
