# Generated by Django 2.2.12 on 2022-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buscador', '0003_auto_20220923_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Id_sheduler',
            new_name='Id_schedule',
        ),
        migrations.AlterField(
            model_name='group',
            name='Id_faculty',
            field=models.ManyToManyField(related_name='Facultys', to='Buscador.Faculty'),
        ),
    ]
