# Generated by Django 2.2.12 on 2022-09-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buscador', '0004_auto_20220923_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Id_schedule',
            field=models.ManyToManyField(related_name='Schedules', to='Buscador.Schedule'),
        ),
    ]
